version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - ./data/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-spring_boot_local}
      - MYSQL_USER=${DB_USER:-spring_user}
      - MYSQL_PASSWORD=${DB_PASS:-spring_secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-spring_secret}
